### ISSUE TITLE
VerticalViewPager with ViewPager

### ISSUE THREAD

**Issue by mbmc** [castorflex/VerticalViewPager#10]
Hello,

I'm using the VerticalViewPager, and one of the Fragment is a ViewPager. Something like this:
View1 - View11 - View12 - View13
View2
View3
View4
View5
It seems to work fine, but when I scroll all the way down, then come back, the views View1 and View11 are gone. But if I scroll all the way to View13, the come back, I can see them again...

I know this is out of the scope of this class, but was just wondering if you had any hint...

thanks!

**Comment by mbmc** [comment]
My bad... In the nested view, I was using getFragmentManage() instead of getChildFragmentManager(). Now it's working :)

**Comment by geelenb** [comment]
can you share your code (in a gist) of how you nest two viewpagers? I can't seem to get it to work.
