### ISSUE TITLE
With added a ListView to VerticalViewPager ,  I found event conflict.

### ISSUE THREAD

**Issue by zondaOf2012** [castorflex/VerticalViewPager#12]
I'll wait for your answer.

**Comment by mradzinski** [comment]
It happens exactly the same if you implement a Swipe gesture on a ListView contained into a regular horizontal ViewPager. On the aforementioned scenario you can override the canScroll method of the ViewPager, however, in your situation I don't think there's a way to determine if the user wants to scroll the ListView or the ViewPager... maybe you can play a bit with requestDisallowInterceptTouchEvent() and see if you can manage to make it work. One way or another, this is most definitively not a bug but the normal behaviour of 1 vertical scrollable view nested into another.
