### ISSUE TITLE
pageAdapter.notifyDataSetChanged() could not let the VerticalViewPager refresh its layout

### ISSUE THREAD

**Issue by origin005x** [castorflex/VerticalViewPager#15]
1. I add some elements to VerticalViewPager.
2. clear the elements and add some new elements
3. use pageAdapter.notifyDataSetChanged(). but it doesn't work.
   why?

**Comment by origin005x** [comment]
this issue has been resolved. Seems that the VerticalViewPager has nothing wrong. The reason for this is that MyPageAdapter did not rewrite the method 'getItemPosition()' from the super class, and the default implementation assumes that items will never change position and always returns. 

So, rewrite this method like this:
int index = mdata.indexOf(object);
return index == -1 ? POSITION_NONE : index;

Hope useful for others.

**Comment by CiprianU** [comment]
also, your adapter should extend FragmentStatePagerAdapter (http://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html) instead of PagerAdapter.
