### ISSUE TITLE
How to set horizontal scrolling

### ISSUE THREAD

**Issue by gilmaman** [castorflex/VerticalViewPager#2]
Im using vert scrolling for landscape mode and still want to use horiz scrolling for portrait
how can i switch between the two?

thanks

**Comment by castorflex** [comment]
Unfortunately at this moment it's only Vertical. If you want to use horizontal scrolling, use the original ViewPager.
I guess you have to use 2 different xml with ViewPager / VerticalViewPager and check programmatically if your view is a ViewPager or a VerticalViewPager. 

``` java
if(mView instanceof ViewPager) ((ViewPager)mView).setAdapter(mAdapter);
else ((VerticalViewPager)mView).setAdapter(mAdapter);
```

You can use the same Adapter though.
