### ISSUE TITLE
set height of every page of ViewPager

### ISSUE THREAD

**Issue by miladrasooli** [castorflex/VerticalViewPager#5]
Hi,
I am using your code in landscape mode and I have `ImageView` in it. the image is big and user needs to scroll vertically. but `VerticalViewPager` goes to next page when scrolling down.
Is there any way to solve this issue?
Thanks

**Comment by castorflex** [comment]
This is probably because your imageview do not intercept touch events.

You can either implement it yourself or use [Photoview](https://github.com/chrisbanes/PhotoView) by @chrisbanes.
Or you can resize your image in landscape mode.
